#!/bin/bash

if [ -d "/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/ntsc-rs.plugin" ]; then
    echo "Signing After Effects plugin with ad-hoc signature..."
    /usr/bin/codesign --force --deep --sign - "/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/ntsc-rs.plugin"
    echo "After Effects plugin signed successfully."
else
    echo "After Effects plugin not found at expected location. Skipping signing."
    exit 1
fi

exit 0
